### ISSUE TITLE
First Release Roadmap

### ISSUE THREAD

**Issue by bloha** [fructo/client-gui-electron#1]
# First Release Roadmap
## Connection with the Native Application
- [ ] By default, the client should use the default port and host.
- [ ] Ask the user to provide port and host if it is impossible to connect using the default values.
- [ ] Provide a way to spawn the native application if it is impossible to connect to it (it is down).
- [ ] Gracefully reopen the connection with a new port and host if the native application (or the user) asked for that.

### Download
- [ ] Ability to download an album.
- [ ] Ability to download all albums of a specified user.
- [ ] Ability to download favorite albums of a specified user.
- [ ] Ability to download search results.
- [ ] Ability to download tagged albums.
- [ ] Ability to watch the download progress.
- [ ] Ability to pause a download process.
- [ ] Ability to resume a paused download process.
- [ ] Ability to abort a download process.

### Upload
- [ ] Ability to upload an album.
- [ ] Ability to watch the upload progress.
- [ ] Ability to pause an upload process.
- [ ] Ability to resume a paused upload process.
- [ ] Ability to abort an upload process.

### Browsing
- [ ] Ability to browse an album.
- [ ] Ability to browse albums of a specified user.
- [ ] Ability to browse favorite albums of a specified user.
- [ ] Ability to browse search results.
- [ ] Ability to browse tagged results.
